### ISSUE TITLE
Is there a way to get logs out of this lib?

### ISSUE THREAD

**Issue by Moar-Chan** [SamuelFisher/torrentcore#12]
I have been unable to download files, it like makes the files and a has file. but it then dies to an error without a log or anything.

also a discord or something could be cool :P

**Comment by SamuelFisher** [comment]
You can configure logging in a similar way to ASP.NET Core - please see here for an example using Serilog:

https://github.com/SamuelFisher/torrentcore/blob/434249c9f1ff61c302c96c68269cb8065dacfe1d/TorrentCore.Cli/Program.cs#L57

TorrentCore uses `Microsoft.Extensions.Logging` so you can use any logging library that implements that.

**Comment by Moar-Chan** [comment]
I got my error, but it might be an error from nyaa.si and this lib interacting?

[getting .torrent onto drive]
https://nyaa.si//download/315335.torrent
C:\Users\moarc\AppData\Local\Temp\tmp7092.tmp.torrent

[Torrent status]
s: Pending
p: 0

[Lib error]
[04:21:37 INF] Contacting tracker
[04:21:37 INF] Announcing to http://nyaa.tracker.wf:7777/announce
[04:21:37 INF] Received response from http://nyaa.tracker.wf:7777/announce
[04:21:37 INF] 1 peers available
[04:21:37 INF] Starting pipeline stage VerifyDownloadedPiecesStage
[04:21:37 ERR] Unhandled exception in pipeline stage VerifyDownloadedPiecesStage
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TorrentCore.Data.Metainfo.FileIndex(Int64 offset, Int64& remainder) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\Metainfo.cs:line 124
   at TorrentCore.Data.BlockDataHandler.TryReadBlockData(Int64 offset, Int64 length, Byte[]& data) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\BlockDataHandler.cs:line 73
   at TorrentCore.Data.PieceCheckerHandler.TryReadBlockData(Int64 offset, Int64 length, Byte[]& data) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\PieceCheckerHandler.cs:line 90
   at TorrentCore.Application.BitTorrent.Pipelines.VerifyDownloadedPiecesStage.HashPiecesData(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\BitTorrent\Pipelines\VerifyDownloadedPiecesStage.cs:line 56
   at TorrentCore.Application.BitTorrent.Pipelines.VerifyDownloadedPiecesStage.Run(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\BitTorrent\Pipelines\VerifyDownloadedPiecesStage.cs:line 41
   at TorrentCore.Application.Pipelines.Pipeline.Run(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\Pipelines\Pipeline.cs:line 34

**Comment by SamuelFisher** [comment]
There was an issue with large torrents which should be fixed in 12911c11778b3d3f967b94c41c6e8ed5c4d6a2c7.

**Comment by Moar-Chan** [comment]
[getting .torrent onto drive]
https://nyaa.si//download/172098.torrent
C:\Users\moarc\AppData\Local\Temp\tmpC440.tmp.torrent

[Lib error]
[02:31:17 INF] Contacting tracker
[02:31:17 INF] Announcing to http://nyaa.tracker.wf:7777/announce
[02:31:17 INF] Received response from http://nyaa.tracker.wf:7777/announce
[02:31:17 INF] 33 peers available
[02:31:17 INF] Starting pipeline stage VerifyDownloadedPiecesStage
[02:31:17 ERR] Unhandled exception in pipeline stage VerifyDownloadedPiecesStage
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TorrentCore.Data.Metainfo.FileIndex(Int64 offset, Int64& remainder) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\Metainfo.cs:line 124
   at TorrentCore.Data.BlockDataHandler.TryReadBlockData(Int64 offset, Int64 length, Byte[]& data) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\BlockDataHandler.cs:line 73
   at TorrentCore.Data.PieceCheckerHandler.TryReadBlockData(Int64 offset, Int64 length, Byte[]& data) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Data\PieceCheckerHandler.cs:line 90
   at TorrentCore.Application.BitTorrent.Pipelines.VerifyDownloadedPiecesStage.HashPiecesData(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\BitTorrent\Pipelines\VerifyDownloadedPiecesStage.cs:line 56
   at TorrentCore.Application.BitTorrent.Pipelines.VerifyDownloadedPiecesStage.Run(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\BitTorrent\Pipelines\VerifyDownloadedPiecesStage.cs:line 41
   at TorrentCore.Application.Pipelines.Pipeline.Run(IStageInterrupt interrupt, IProgress`1 progress) in C:\Users\moarc\Source\Repos\SamuelFisher\torrentcore\TorrentCore\Application\Pipelines\Pipeline.cs:line 34

**Comment by Moar-Chan** [comment]
This might be an enviroment error but its just telling me it can't connect, maybe you could try the torrent to see if its my host enviroment?

[getting .torrent onto drive]
C:\Users\moarc\AppData\Local\Temp\tmp22E2.tmp.torrent
https://nyaa.si//download/172098.torrent

[Lib error]
[02:37:09 INF] Contacting tracker
[02:37:09 INF] Announcing to http://nyaa.tracker.wf:7777/announce
[02:37:09 INF] Received response from http://nyaa.tracker.wf:7777/announce
[02:37:09 INF] 32 peers available
[02:37:09 INF] Starting pipeline stage VerifyDownloadedPiecesStage
[02:37:10 INF] 0 pieces already downloaded
[02:37:10 INF] Finished pipeline stage VerifyDownloadedPiecesStage
[02:37:10 INF] Starting pipeline stage DownloadPiecesStage
[02:37:11 INF] Connected to peer at 23.226.128.226:51413
[02:37:11 INF] Discarded duplicate peer 70.30.235.135:55308
[02:37:31 INF] Failed to connect to peer at 5.18.164.127:27596
[02:37:31 INF] Failed to connect to peer at 5.29.23.248:38699
[02:37:31 INF] Failed to connect to peer at 45.56.154.138:8999
[02:37:32 INF] Connected to peer at 51.38.13.247:53822
[02:37:42 INF] Disconnected from peer at 23.226.128.226:51413
[02:37:52 INF] Failed to connect to peer at 10.35.0.82:6881
[02:37:52 INF] Failed to connect to peer at 69.203.82.69:51413
[02:37:53 INF] Connected to peer at 70.30.235.135:55308

**Comment by Moar-Chan** [comment]
I got it to work
thx for the help!
